<?php

/**
 * Form Builder extension
 *
 * @category   Linhnv
 * @package    Linhnv_ChatSystem
 * @author     Landofcoder Dev Team <landofcoder@gmail.com>
 */
?>
<div class="landofcoder-fue-menu">
    <div class="actions dropdown closable">
        <button type="button" class="admin__action-dropdown" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
            <span class="admin__action-dropdown-text"><?= $block->getCurrentItem()['title'] ?></span>
        </button>
        <ul class="dropdown-menu">
            <?php foreach ($block->getMenuItems() as $index => $item): ?>
                <li class="<?php if ($block->isCurrent($index)): ?>current<?php endif; ?> <?php if (isset($item['separator'])): ?>separator<?php endif; ?>" >
                    <a <?php if(isset($item['item'])){ echo 'class="Linhnv-dropdown"'; } ?>  href="<?= $item['url'] ?>" <?= $block->renderAttributes($item) ?>><?= $item['title'] ?><?php if(isset($item['item'])){ echo '<span class="opener" ></span>'; } ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
