<?php
/**
 * @var $block \Linhnv\ChatSystem\Block\Adminhtml\Chat\Edit\Tab\ChatGPT
 */
$this->isRead();
$helper = $this->helper("Linhnv\ChatSystem\Helper\Data");
$current_url = $block->escapeUrl($this->getCurrentChat()->getData('current_url'));
?>
<p><?= __('Chat message sent on') . ' ' . ($current_url ? ('<a href="' . $current_url . '" target="_BLANK">' . $current_url . '</a>') : ""); ?></p>
<div class="main-chat-gpt" id="main-chat-gpt">
</div>
<div class="box-chat ChatGpt">
    <form method="post" id="formSendMegChatGpt" onsubmit="return false;">
        <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($this->getFormKey()); ?>">
        <input type="hidden" name="chat_id" value="<?= $block->escapeHtmlAttr($this->getCurrentChat()->getData('chat_id')); ?>">
        <input type="text" name="body_msg" placeholder="<?= __('Please enter a message'); ?> ...">
    </form>
</div>
<style>
    .main-chat-gpt {height: 200px;padding: 38px 10px 38px 10px;overflow-y: scroll;}
    .main-chat-gpt .msg-user {width: 100%; text-align: right;}
    .main-chat-gpt .msg-user p {background-color: #428bca; color: #fff; display: inline-block; padding: 10px; font-size: 15px;}
    .main-chat-gpt .msg {width: 100%; text-align: left; margin-bottom: 10px;}
    .main-chat-gpt .msg p {background-color: #f1f1f1; color: #555; display: inline-block; padding: 10px; font-size: 15px;}
    .main-chat-gpt .msg-user .info-msg-user,
    .main-chat-gpt .msg .info-msg {font-size: 13px; color: #666; margin-top: 5px;}
</style>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {

        function sendMsg() {
            $body_msg = linhnvescapeHtml($('#formSendMegChatGpt input[name="body_msg"]').val());
            $chat_id = linhnvescapeHtml($('#formSendMsg input[name="chat_id"]').val());
            if ($.trim($body_msg)) {
                $('#formSendMsg input[type="text"]').val('');
                $('.main-chat').append('<div class="msg-user"><p>' + $body_msg + '</p><div class="info-msg-user"><?= __("You");?></div></div>');
                $.ajax({
                    url: '<?= $this->getUrl('linhnvchatsystem/chat/sendmsgchatgpt'); ?>',
                    type: 'post',
                    dataType: 'json',
                    data: {
                        body_msg: $body_msg,
                        chat_id: $chat_id,

                    }, success: function () {
                        $('#formSendMegChatGpt input[type="text"]').val('');
                        var div = document.getElementById('main-chat-gpt')
                        div.scrollTop = div.scrollHeight - div.clientHeight;
                    }
                });
            }
        }

        function linhnvescapeHtml(unsafe) {
            return unsafe
                .replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;")
                .replace(/"/g, "&quot;")
                .replace(/'/g, "&#039;");
        }

        $('#formSendMegChatGpt input[type="text"]').keypress(function () {
            var keycode = (event.keyCode ? event.keyCode : event.which);
            if (keycode == '13') {
                sendMsg();
                var div = document.getElementById('main-chat-gpt')
                div.scrollTop = div.scrollHeight - div.clientHeight;
            }
        });

        $('#formSendMegChatGpt input[type="text"]').click(function (e) {
            var div = document.getElementById('main-chat-gpt')
            div.scrollTop = div.scrollHeight - div.clientHeight;
        });
        //
        //$('.main-chat').load('<?php //= $this->getUrl('linhnvchatsystem/chat/msglog/chat_id/' . $this->getCurrentChat()->getData('chat_id')); ?>//');
        //$.ajaxSetup({cache: false});
        //setInterval(function () {
        //    $('.main-chat').load('<?php //= $this->getUrl('linhnvchatsystem/chat/msglog/chat_id/' . $this->getCurrentChat()->getData('chat_id')); ?>//');
        //}, 5000);
    });
</script>
